version: 2
updates:
  # Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly

  # Spring Boot
  - package-ecosystem: maven
    directory: "/java/spring-boot"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: org.apache.maven:*
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"

  # Quarkus
  - package-ecosystem: maven
    directory: "/java/quarkus"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: org.apache.maven:*
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"

  # Node.js
  - package-ecosystem: npm
    directory: "/nodejs/messaging-api"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: npm
    directory: "/nodejs/preval"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: npm
    directory: "/nodejs/swiftref"
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"

  # dotnet
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "monthly"
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"

  # python
  - package-ecosystem: "pip"
    directory: "/python/messaging-api"
    schedule:
      interval: "monthly"
    groups:
      minor-changes:
        update-types:
        - "minor"
        - "patch"

  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
