swift:
  base-url: https://sandbox.swift.com
  endpoint: ${swift.base-url}/swiftrefdata/v4
  oauth2:
    username: sandbox-id
    password: sandbox-key
  # Proxy settings, uncomment to enable proxy
  #proxy:
  #  host: myproxy.corp
  #  port: 48600

spring:
  security:
    oauth2:
      client:
        registration:
          swift:
            client-id: ${CONSUMER_KEY}
            client-secret: ${CONSUMER_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: password
        provider:
          swift:
            token-uri: ${swift.base-url}/oauth2/v1/token
  # Before deploying to production
  #   1. Download SwiftNet Root CA https://www2.swift.com/knowledgecentre/kb_articles/5024117
  #   2. Rename the downloaded file to swift_ca.crt and copy the file to the resources folder
  #   3. Uncomment below lines to make a request in production
  #ssl:
  #  bundle:
      #pem:
      #  client:
      #    truststore:
      #      certificate: classpath:swift_ca.crt

springdoc:
  swagger-ui:
    path: /test
    defaultModelRendering: model
    defaultModelsExpandDepth: -1

logging:
  level:
    org.apache.hc.client5.http.headers: DEBUG